### ISSUE TITLE
I can not uninstall the extension 

### ISSUE THREAD

**Issue by amalakkad93** [willasm/project-notes#4]
how I can uninstall this extension. When I uninstall it  and restart vs code, the extension is still there

**Comment by willasm** [comment]
That is strange? VSCode handles the install and uninstall of extensions itself. Are you following this [method](https://code.visualstudio.com/docs/editor/extension-marketplace#_uninstall-an-extension) to uninstall? You could also try deleting the extensions folder `willasm.project-notes-1.5.0` directly (while vscode is closed). It should be in under `%USERPROFILE%\.vscode\extensions`.

**Comment by amalakkad93** [comment]
when i type %USERPROFILE%\.vscode\extensions in my file explorer search bar, then when i search willasm.project-notes-1.5.0 it tells me NO items match your search.

**Comment by willasm** [comment]
Your missing the backslash after %USERPROFILE% it should be %USERPROFILE%\.vscode\extensions

That's strange Github is stripping the backslash out in the line above?

**Comment by willasm** [comment]
The full location is `C:\Users\<yourusername>\.vscode\extensions`

**Comment by amalakkad93** [comment]
I typed that and still it is not there. C:\Users\<yourusername>\.vscode\extensions\willasm.project-notes-1.5.0

**Comment by willasm** [comment]
Are you replacing `<yourusername>` with your actual user name?

**Comment by amalakkad93** [comment]
yes of course.

**Comment by willasm** [comment]
Here is an easier way to find it. Within VSCode, press ctrl + shift + p, and type: "Open Extension Folder". That will open the extensions folder in file explorer. Then close vscode and then delete the extensions folder. (willasm.project-notes-1.5.0)

**Comment by willasm** [comment]
Please do note that you must have some issue with either vscode or windows itself as extensions have no way to control the install or uninstall process. That is completely handled by vscode itself. Here is a [Youtube Video](https://www.youtube.com/watch?v=5Ziq9MxbvSs) showing how to remove an extension to help you as a guide. Let me know if it works.

**Comment by amalakkad93** [comment]
I figured out what was the problem. It turns out that I have to unchecked from the activity bar first before uninstall the extension.  Thanks for your help

**Comment by willasm** [comment]
Glad you solved the issue.
