### ISSUE TITLE
Extension is incompatible with POSIX paths (i.e. Linux and macOS)

### ISSUE THREAD

**Issue by danielskowronski** [willasm/project-notes#5]
Type: <b>Bug</b>

- start on empty VS Code profile with no extensions
- install this extension
- attempt to add gloabal or local note from sidebar or command bar
- attempt to add `note.md` file manually under `~/.pnotes`
- nothing happens

Sometimes `Error running command project-notes.newGlobalNote: command 'project-notes.newGlobalNote' not found. This is likely caused by the extension that contributes project-notes.newGlobalNote.` pops up.

Extension version: 1.5.0
VS Code version: Code 1.83.1 (Universal) (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:46:55.789Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 6, 6|
|Memory (System)|32.00GB (0.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by danielskowronski** [comment]
After extension reload, it was able to read manually created note under `~/.pnotes`. 

And I found what the issue is - **this extension is forcibly hardcoded to work only with Windows**, where path elements are delimited by `\`. 

POSIX-compatible OSes like macOS or Linux happily create files like `project_name\.pnotes\test2.md` and in most cases those files would be read, but it seems like whatever library is used here, it attempts to read them from the project directory; however, files are created at the parent directory. I strongly advise using a proper library to construct paths, not all filesystems use `\` or `/` - sometimes it's even `¥` :)

**Comment by willasm** [comment]
So sorry to not get back to you sooner but I have been without a computer for a while unfortunately. What OS are you running? As far as I know VSCode only runs on Mac, Linux and Windows and none of them should have a problem with the paths? Did you try running the command `Project Notes: Set Globals Notes Folder Location` from the command palette first? I would like to solve this issue before I continue with my plans for this extension. I don't actually use any library for this, just calls to VSCodes API and vanilla JavaScript. I do append '\\' to the returned folders and I probably should have used '/' as Windows will work with those just fine.

I do plan on separating this extension into 2 anyways as the Todo highlighting, which was originally meant to be just a very small addition to the extension, has grown to be worthy of a stand alone extension in its own right. I had already began working on this when my computer died on me, but now that I have replaced it I want to continue where I left off. When both are completed this extension will be retired. I do appreciate all suggestions that you can offer and I would like to make my extensions as OS cross compatible as possible.

**Comment by RichPC** [comment]
As @danielskowronski has said, this doesn't work on Linux.

Using Set Local Notes Folder Location
 or 
Set Global Notes Folder Location doesn't help.

**Comment by willasm** [comment]
I just uploaded a test package 'project-notes-1.5.0-LinuxTest.vsix' in the root of the repo. Can you please download this and install it over the current version and let me know if this fixes the issue. (Use the install from vsix command to do this). Thanks for bringing this up. I had been meaning to fix this for a very long time now but got sidetracked and it just got pushed further down my todo list. I still intend to do a complete rewrite of this extension and separate this into 2 different extensions. As I'm caught up on all my other projects I intend to start on this project next.

Thanks, William.

**Comment by RichPC** [comment]
Hi William,

Thanks for the vsix file. The extension works on Linux Ubuntu now.  My new
local note got created in the project's root directory in a directory
called project_notes, and my note showed in the list of local notes in the
side panel, and reopened from the side panel.

FYI I was looking for an extension like this for continuity reminders, e.g.
Friday afternoon notes for Monday morning pickup, sort of thing.

Thanks for your fast response.

Kind Regards,
Richard

**Comment by willasm** [comment]
Thanks for letting me know it is working. I will upload the fixed version later today.

**Comment by willasm** [comment]
I am closing this as completed. Important note: This extension will no longer be updated. The extension has been split into 2 extensions now. See the README.md for details.

Thanks William.
