### ISSUE TITLE
after VS acc sych wont start up 

### ISSUE THREAD

**Issue by As-Tomas** [willasm/project-notes#6]
Type: <b>Bug</b>

after VS acc sych wont start up in new pc.
in list of extensions says Activating...

when try to create note:
Error running command project-notes.newProjectNote: command 'project-notes.newProjectNote' not found. This is likely caused by the extension that contributes project-notes.newProjectNote.

Extension version: 1.7.0
VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-1355U (12 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.64GB (10.60GB free)|
|Process Argv|--crash-reporter-id ea7ee3df-7004-4293-8db4-7399a7a8bc0e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
ccpltc:31103427
pythonrstrctxt:31103193
wkspc-onlycs-c:31106320

```

</details>

**Comment by willasm** [comment]
Can you have a look at the extensions settings. There are 2 settings, `Global Notes Folder` and `Local Notes Folder` and let me know what they are set to. I already can see that there will be an issue with the global notes as they will not be copied to the new machine as they can be set to any location on your computer and vscode sync will not copy them to the new machine as they are actually not part of the extension. You would have to manually copy those over yourself. The `global Notes Folder` is most likely set to a location that does not exist on the new machine. Try copying the global notes folder over to the new machine and set the Global Notes Folder to point to the new folder location and see if it works after that.

**Comment by As-Tomas** [comment]
Now I see that on first, main pc it does not working too>
[image: image.png]
settings
[image: image.png]
File exists but empty
[image: image.png]
Mvh | Best regards
Tomas Bance

**Comment by willasm** [comment]
Can you try posting the images again as that would help a lot. They are not displaying for me. It just shows `[image: image.png]` for all 3. Try using a unique name for each image.

Thanks, William.

**Comment by As-Tomas** [comment]
Images by order
https://drive.google.com/file/d/13zPAGUpapJeSJanK6HeLv7hj4H1fuokv/view?usp=drivesdk

https://drive.google.com/file/d/1c9EAMlLQ8u9ZdGQosCqgnqSyq3HxMFH7/view?usp=drivesdk

https://drive.google.com/file/d/1YsBSQZ1qXfacVFbQpDE3fZwlpZQ2Qfxv/view?usp=drivesdk

**Comment by willasm** [comment]
The folder location for global notes is most likely wrong. You have it set to `c:\Users\UserName\.pnotes`. The UserName should be your Windows user name, the name you are logged in as. For example, mine would be `c:\Users\William\.pnotes`. If you are not sure what it is you can find it in the start menu, left hand side, the very top button.

Thanks, William

**Comment by As-Tomas** [comment]
Cmon, don't be so basic, I know my username. The fact it's not wrong and
nothing to deal with path.

**Comment by willasm** [comment]
So your user name is 'UserName'? No insult was intended. You would be surprised how many people do make that mistake. Anyhow, try creating a markdown file in that folder directly. The contents do not matter just create 'somenote.md' in the folder and restart vscode and see if you still get an error. the note should appear in the list of notes.

Thanks, William
